//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza_kliens.PizzaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Topping", Namespace="http://schemas.datacontract.org/2004/07/Pizza")]
    [System.SerializableAttribute()]
    public partial class Topping : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pizza", Namespace="http://schemas.datacontract.org/2004/07/Pizza")]
    [System.SerializableAttribute()]
    public partial class Pizza : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] toppingsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] toppings {
            get {
                return this.toppingsField;
            }
            set {
                if ((object.ReferenceEquals(this.toppingsField, value) != true)) {
                    this.toppingsField = value;
                    this.RaisePropertyChanged("toppings");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PizzaService.IPizzaService")]
    public interface IPizzaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaService/OrderPizza", ReplyAction="http://tempuri.org/IPizzaService/OrderPizzaResponse")]
        int OrderPizza(int pizzaid, string address, int transferprice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaService/OrderPizza", ReplyAction="http://tempuri.org/IPizzaService/OrderPizzaResponse")]
        System.Threading.Tasks.Task<int> OrderPizzaAsync(int pizzaid, string address, int transferprice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaService/getToppings", ReplyAction="http://tempuri.org/IPizzaService/getToppingsResponse")]
        Pizza_kliens.PizzaService.Topping[] getToppings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaService/getToppings", ReplyAction="http://tempuri.org/IPizzaService/getToppingsResponse")]
        System.Threading.Tasks.Task<Pizza_kliens.PizzaService.Topping[]> getToppingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaService/getPizzas", ReplyAction="http://tempuri.org/IPizzaService/getPizzasResponse")]
        Pizza_kliens.PizzaService.Pizza[] getPizzas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaService/getPizzas", ReplyAction="http://tempuri.org/IPizzaService/getPizzasResponse")]
        System.Threading.Tasks.Task<Pizza_kliens.PizzaService.Pizza[]> getPizzasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPizzaServiceChannel : Pizza_kliens.PizzaService.IPizzaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PizzaServiceClient : System.ServiceModel.ClientBase<Pizza_kliens.PizzaService.IPizzaService>, Pizza_kliens.PizzaService.IPizzaService {
        
        public PizzaServiceClient() {
        }
        
        public PizzaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PizzaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PizzaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PizzaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int OrderPizza(int pizzaid, string address, int transferprice) {
            return base.Channel.OrderPizza(pizzaid, address, transferprice);
        }
        
        public System.Threading.Tasks.Task<int> OrderPizzaAsync(int pizzaid, string address, int transferprice) {
            return base.Channel.OrderPizzaAsync(pizzaid, address, transferprice);
        }
        
        public Pizza_kliens.PizzaService.Topping[] getToppings() {
            return base.Channel.getToppings();
        }
        
        public System.Threading.Tasks.Task<Pizza_kliens.PizzaService.Topping[]> getToppingsAsync() {
            return base.Channel.getToppingsAsync();
        }
        
        public Pizza_kliens.PizzaService.Pizza[] getPizzas() {
            return base.Channel.getPizzas();
        }
        
        public System.Threading.Tasks.Task<Pizza_kliens.PizzaService.Pizza[]> getPizzasAsync() {
            return base.Channel.getPizzasAsync();
        }
    }
}
